name: Build site

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Fix git pull
        run: git config --global url."https://".insteadOf git://

      - name: 📂 setup
        uses: actions/checkout@v4

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
          bundler-cache: true

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Build report
        run: |
          bundle exec ./bin/report_generator.rb
          tar zcvf report.tar.gz latex_out

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website and report sources
          path: |
            report.tar.gz
            _site

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
